# Generated by Django 5.2.10 on 2026-02-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_address',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_admin',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_author',
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('account_holder', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_bank_transfer',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_category',
            },
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=255)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'core_credit_card_payment',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('method_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_discount',
            },
        ),
        migrations.CreateModel(
            name='EWalletPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('pay_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_ewallet_payment',
            },
        ),
        migrations.CreateModel(
            name='MembershipLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('required_points', models.IntegerField()),
                ('benefit_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_membership_level',
            },
        ),
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_url', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'core_promotion_event',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_publisher',
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desc', models.TextField(blank=True, null=True)),
                ('total_customer', models.IntegerField()),
            ],
            options={
                'db_table': 'core_revenue_report',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dstaff', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_staff',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_translator',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_user',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(max_length=255, unique=True)),
                ('max_usage', models.IntegerField()),
                ('current_usage', models.IntegerField(default=0)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'core_voucher',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'core_warehouse',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('format', models.CharField(max_length=50)),
                ('download_link', models.CharField(max_length=255)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook', to='core.book')),
            ],
            options={
                'db_table': 'core_audio_book',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author'),
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('image_type', models.CharField(max_length=50)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.book')),
            ],
            options={
                'db_table': 'core_book_image',
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('books', models.ManyToManyField(related_name='series', to='core.book')),
            ],
            options={
                'db_table': 'core_book_series',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='core.category'),
        ),
        migrations.CreateModel(
            name='CustomerAnalytic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('favorite_genre', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.customer')),
            ],
            options={
                'db_table': 'core_customer_analytic',
            },
        ),
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('format', models.CharField(max_length=50)),
                ('download_link', models.CharField(max_length=255)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebook', to='core.book')),
            ],
            options={
                'db_table': 'core_ebook',
            },
        ),
        migrations.CreateModel(
            name='InventoryStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
            options={
                'db_table': 'core_inventory_stat',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membershiplevel'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.customer')),
            ],
            options={
                'db_table': 'core_notification',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer')),
            ],
            options={
                'db_table': 'core_order',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='core.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'db_table': 'core_order_history',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order')),
            ],
            options={
                'db_table': 'core_payment',
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('customer_id_str', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='core.customer')),
            ],
            options={
                'db_table': 'core_point_history',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.publisher'),
        ),
        migrations.CreateModel(
            name='RatingStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('host_customer', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_stats', to='core.book')),
            ],
            options={
                'db_table': 'core_rating_stat',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='core.order')),
            ],
            options={
                'db_table': 'core_shipping',
            },
        ),
        migrations.CreateModel(
            name='StockInBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_records', to='core.book')),
            ],
            options={
                'db_table': 'core_stock_in_book',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('total_import_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
            ],
            options={
                'db_table': 'core_supplier',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.translator'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_available', models.IntegerField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.book')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='core.warehouse')),
            ],
            options={
                'db_table': 'core_inventory',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='core.customer')),
            ],
            options={
                'db_table': 'core_wishlist',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.customer')),
            ],
            options={
                'db_table': 'core_rating',
                'unique_together': {('customer', 'book')},
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.wishlist')),
            ],
            options={
                'db_table': 'core_wishlist_item',
                'unique_together': {('wishlist', 'book')},
            },
        ),
    ]
